# Generated by Django 5.0.6 on 2024-06-10 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movies',
            new_name='Movie',
        ),
    ]
