# Generated by Django 5.0.6 on 2024-06-13 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0003_alter_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
