# Generated by Django 5.0.6 on 2024-06-14 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0005_streamplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='imdb_app.streamplatform'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='website',
            field=models.URLField(),
        ),
    ]
